CREATE TABLE creditcard(
Time TIMESTAMP,
Spending_Pattern1 FLOAT,
Spending_Pattern2 FLOAT,
Spending_Pattern3 FLOAT,
Spending_Pattern4 FLOAT,
Spending_Pattern5 FLOAT,
Spending_Pattern6 FLOAT,
Spending_Pattern7 FLOAT,
Spending_Pattern8 FLOAT,
Spending_Pattern9 FLOAT,
Spending_Pattern10 FLOAT,
Spending_Pattern11 FLOAT,
Spending_Pattern12 FLOAT,
Spending_Pattern13 FLOAT,
Spending_Pattern14 FLOAT,
Spending_Pattern15 FLOAT,
Spending_Pattern16 FLOAT,
Spending_Pattern17 FLOAT,
Spending_Pattern18 FLOAT,
Spending_Pattern19 FLOAT,
Spending_Pattern20 FLOAT,
Spending_Pattern21 FLOAT,
Spending_Pattern22 FLOAT,
Spending_Pattern23 FLOAT,
Spending_Pattern24 FLOAT,
Spending_Pattern25 FLOAT,
Spending_Pattern26 FLOAT,
Spending_Pattern27 FLOAT,
Spending_Pattern28 FLOAT,
Amount FLOAT,
Class BOOLEAN,
Z_score FLOAT,
Amount_anomaly INT,
Transaction_id INT PRIMARY KEY,
Merchant_id INT,
FOREIGN KEY (Merchant_id) REFERENCES merchants(id)
);

SELECT *
FROM creditcard;